# Generated by Django 4.2.1 on 2023-10-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_recurring_bill_recurringbill_item_repeatevery'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='comments',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
